spring:
  datasource:
    url: jdbc:mysql://43.200.191.196:3306/lotteon?serverTimezone=Asia/Seoul
    username: root
    password: "qwer1234!Q"
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
  servlet:
    multipart:
      location: uploads/
  data:
    redis:
      host: 43.200.191.196
      port: 6379
      password: 'qwer1234!Q'
decorator:
  datasource:
    p6spy:
      enable-logging: false